disallowMessage: "Sorry, access to this is restricted at the moment."
level1disabledCommands:
  - achievement
  - ban
  - "ban-ip"
  - blockdata
  - clear
  - clone
  - debug
  - defaultgamemode
  - deop
  - difficulty
  - effect
  - enchant
  - entitydata
  - execute
  - fill
  - gamemode
  - gamerule
  - give
  - kick
  - op
  - pardon
  - "pardon-ip"
  - particle
  - playsound
  - reload
  - replaceitem
  - restart
  - "save-all"
  - "save-off"
  - "save-on"
  - seed
  - setblock
  - setidletimeout
  - setworldspawn
  - spawnpoint
  - spreadplayers
  - stop
  - summon
  - testfor
  - testforblock
  - testforblocks
  - time
  - timings
  - toggledownfall
  - tp
  - trigger
  - version
  - weather
  - whitelist
  - worldborder
  - xp
level2disabledCommands:
  - achievement
  - ban
  - "ban-ip"
  - blockdata
  - clone
  - debug
  - defaultgamemode
  - deop
  - enchant
  - entitydata
  - execute
  - fill
  - kick
  - op
  - pardon
  - "pardon-ip"
  - particle
  - playsound
  - reload
  - replaceitem
  - restart
  - "save-all"
  - "save-off"
  - "save-on"
  - seed
  - setblock
  - setidletimeout
  - setworldspawn
  - spawnpoint
  - spreadplayers
  - stop
  - summon
  - testfor
  - testforblock
  - testforblocks
  - time
  - timings
  - toggledownfall
  - trigger
  - version
  - weather
  - whitelist
  - worldborder
  - xp
level3disabledCommands:
  - achievement
  - blockdata
  - clone
  - debug
  - defaultgamemode
  - enchant
  - entitydata
  - execute
  - fill
  - particle
  - playsound
  - reload
  - replaceitem
  - restart
  - "save-all"
  - "save-off"
  - "save-on"
  - seed
  - setblock
  - setidletimeout
  - setworldspawn
  - spawnpoint
  - spreadplayers
  - stop
  - summon
  - testfor
  - testforblock
  - testforblocks
  - time
  - timings
  - toggledownfall
  - trigger
  - version
  - weather
  - whitelist
  - worldborder
  - xp
level4disabledCommands: []